AWSTemplateFormatVersion: '2010-09-09'

Description: This example stack contains an SNS topic that pushes to an SQS queue.

Parameters:

  SqsArn:
    Type: String
    Description: Arn of and SQS queue

Resources:

  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref SqsArn
          Protocol: sqs